use project;
select * from retailstore;
-- Q1. What is the total revenue generated by male vs. female customers?
select gender,sum(Purchase_Amount_USD) as total_revenue_generated
from retailstore
group by gender;
-- Q2. Which customers used a discount but still spent more than the average purchase amount?
SELECT Customer_ID, Purchase_Amount_USD
FROM retailstore
WHERE Promo_Code_Used = 'Yes'
group by Customer_ID, Purchase_Amount_USD
HAVING Purchase_Amount_USD > (
    SELECT AVG(Purchase_Amount_USD)
    FROM retailstore
);
-- Q3. Which are the top 5 products with the highest average review rating?
select Item_Purchased,avg(Review_Rating) as AVG_review_rating
FROM retailstore
group by Item_Purchased,Review_Rating
order by avg(Review_Rating) desc
limit 5;
-- Q4. Compare the average Purchase Amount between Standard and Express Shipping.
select avg(Purchase_Amount_USD) as avg_purchase, Shipping_Type
FROM retailstore
where Shipping_Type  in ('Express','Standard')
group by Shipping_Type;
-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
select Subscription_Status,avg(Purchase_Amount_USD) as avg_purchase, sum(Purchase_Amount_USD) as total_revenue_generated 
FROM retailstore
group by Subscription_Status;
-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT Item_Purchased,Promo_Code_Used,

       COUNT(Previous_Purchases) * 100.0 /
       (SELECT COUNT(Previous_Purchases) FROM retailstore) AS purchase_percentage

FROM retailstore
where Promo_Code_Used='Yes'
GROUP BY Item_Purchased
ORDER BY purchase_percentage DESC
limit 5;
-- Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
select  Customer_ID, Previous_Purchases,
CASE
    WHEN Previous_Purchases  between 1 and 20 THEN "New"
    WHEN Previous_Purchases between 21 and 40 THEN"Returning"
    ELSE  "Loyal"
END as Customer_type
FROM retailstore;

-- Q8. What are the top 3 most purchased products within each category?
with top3 as
( select Category,Item_Purchased,count(*)as Total_Customers,
   dense_rank() over (partition by Category order by count(*)) as rnk
   FROM retailstore
   group by Category,Item_Purchased
   
)
select Category,Item_Purchased,Total_Customers
from top3
where rnk<3;
-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select Subscription_Status,
count(*)as Total_Customers,avg(Purchase_Amount_USD) as avg_purchase
FROM retailstore
where Previous_Purchases>5
group by Subscription_Status;
-- Q10. What is the revenue contribution of each age group?
select age_group , sum(Purchase_Amount_USD) as total_revenue_generated
from retailstore
group by age_group;